site_name: Trabalho Final - Engenharia de Dados
site_description: Documentação oficial do projeto do Data Lakehouse
site_author: luiz antonio cardoso, alexandre sartore teixeira, cristófer figurédo martins, davi carlos freitas, guilherme zapelíni da rosa schwa, tiago silvia de bittencourt
site_url: https://luizantoniocardoso.github.io/trabalho-final-eng-dados/
repo_url: https://github.com/luizantoniocardoso/trabalho-final-eng-dados

theme:
  name: material
  language: pt-BR
  palette:
    - scheme: default
      primary: blue
      accent: indigo

nav:
  - Início: index.md
  - Arquitetura:
      - Visão Geral: arquitetura.md
  - Ingestão:
      - Estratégia de Ingestão: ingestao.md

  - Modelagem de Dados:
      - Modelo Conceitual: modelo_conceitual.md
      - Modelo Físico (DDL): modelo_fisico.md
  - Modelo Dimensional:
      - Estrutura Dimensional: modelo_dimensional.md
  - Dashboard:
      - Visualizações: dashboard.md
