site_name: Trabalho Final - Engenharia de Dados
site_description: Documentação oficial do projeto do Data Lakehouse
site_author: Sua Equipe
repo_url: https://github.com/luizantoniocardoso/trabalho-final-eng-dados

theme:
  name: material
  language: pt-BR
  palette:
    - scheme: default
      primary: blue
      accent: indigo

nav:
  - Início: index.md
  - Domínio do Projeto: dominio.md
  - Arquitetura:
      - Visão Geral: arquitetura.md
  - Ingestão:
      - Estratégia de Ingestão: ingestao.md
  - Transformações:
      - Bronze / Silver / Gold: transformacoes.md
  - Modelo Dimensional:
      - Estrutura Dimensional: modelo_dimensional.md
  - Dashboard:
      - Visualizações: dashboard.md
